# action.yml
name: 'Upload-Files-Action'
description: 'Upload file to your server use sftp & ssh private key'
inputs:
  username:
    description: 'username'
    required: true
  server:  
    description: 'your sftp server'
    required: true
  port: 
    description: 'your sftp server port, default to 22'
    required: true
    default: "22"
  ssh_private_key:
    description: 'you can copy private_key from your *.pem file, keep format'
    required: true
  local_path:
    description: 'Path to upload file'
    required: true
    default: ./*
  target_path:
    description: 'Server target path'
    required: true
    default: /

  args:
    description: 'sftp args'
    required: false


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.server }}
    - ${{ inputs.port }}
    - ${{ inputs.ssh_private_key }}
    - ${{ inputs.local_path }}
    - ${{ inputs.target_path }}
    - ${{ inputs.args }}

branding:
  icon: 'upload-cloud'  
  color: 'purple'
